# Generated by Django 5.1.5 on 2025-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
